export interface AgentDTO {
  ideAgente: number,
  codTipoRemite: string,
  codTipoPers: string,
  nombre: string,
  nroDocumentoIden: string,
  razonSocial: string,
  nit: string,
  codCortesia: string,
  codCargo: string,
  codEnCalidad: string,
  codTipDocIdent: string,
  nroDocuIdentidad: string,
  codSede: string,
  codDependencia: string,
  codFuncRemite: string,
  fecAsignacion: Date,
  ideContacto: number,
  codTipAgent: string,
  indOriginal: string
}
