export interface ContactoDTO {
  ideContacto: number,
  nroViaGeneradora: string,
  nroPlaca: string,
  codTipoVia: string,
  codPrefijoCuadrant: string,
  codPostal: string,
  direccion: string,
  celular: string,
  telFijo1: string,
  telFijo2: string,
  extension1: string,
  extension2: string,
  corrElectronico: string,
  codPais: string,
  codDepartamento: string,
  codMunicipio: string,
  provEstado: string,
  ciudad: string
}
