
package co.com.soaint.funcionario.apis.delegator.security.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecurityAPI", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecurityAPI {


    /**
     * 
     * @param uid
     * @return
     *     returns wsclient.ListadoRoles
     */
    @WebMethod(action = "getRolesbyUser")
    @WebResult(name = "getRolesbyUser", targetNamespace = "")
    @RequestWrapper(localName = "getRolesbyUser", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.GetRolesbyUser")
    @ResponseWrapper(localName = "getRolesbyUserResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.GetRolesbyUserResponse")
    public ListadoRoles getRolesbyUser(
            @WebParam(name = "uid", targetNamespace = "")
            String uid);

    /**
     * 
     * @param rol
     * @return
     *     returns wsclient.OperationPrincipalContextListStatus
     */
    @WebMethod(action = "obtenerUsuariosporRol")
    @WebResult(name = "obtenerUsuariosporRol", targetNamespace = "")
    @RequestWrapper(localName = "obtenerUsuariosporRol", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.ObtenerUsuariosporRol")
    @ResponseWrapper(localName = "obtenerUsuariosporRolResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.ObtenerUsuariosporRolResponse")
    public OperationPrincipalContextListStatus obtenerUsuariosporRol(
            @WebParam(name = "rol", targetNamespace = "")
            String rol);

    /**
     * 
     * @param rol
     * @return
     *     returns wsclient.OperationStatus
     */
    @WebMethod(action = "eliminarRol")
    @WebResult(name = "eliminarRol", targetNamespace = "")
    @RequestWrapper(localName = "eliminarRol", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.EliminarRol")
    @ResponseWrapper(localName = "eliminarRolResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.EliminarRolResponse")
    public OperationStatus eliminarRol(
            @WebParam(name = "rol", targetNamespace = "")
            String rol);

    /**
     * 
     * @return
     *     returns wsclient.OperationRolesListStatus
     */
    @WebMethod(action = "listadoDeRoles")
    @WebResult(name = "listadoDeRoles", targetNamespace = "")
    @RequestWrapper(localName = "listadoDeRoles", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.ListadoDeRoles")
    @ResponseWrapper(localName = "listadoDeRolesResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.ListadoDeRolesResponse")
    public OperationRolesListStatus listadoDeRoles();

    /**
     * 
     * @param usuario
     * @param rol
     * @return
     *     returns wsclient.OperationStatus
     */
    @WebMethod(action = "crearRol")
    @WebResult(name = "crearRol", targetNamespace = "")
    @RequestWrapper(localName = "crearRol", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.CrearRol")
    @ResponseWrapper(localName = "crearRolResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.CrearRolResponse")
    public OperationStatus crearRol(
            @WebParam(name = "rol", targetNamespace = "")
            Rol rol,
            @WebParam(name = "usuario", targetNamespace = "")
            String usuario);

    /**
     * 
     * @param usuario
     * @return
     *     returns wsclient.OperationStatus
     */
    @WebMethod(action = "actualizarUsuario")
    @WebResult(name = "actualizarUsuario", targetNamespace = "")
    @RequestWrapper(localName = "actualizarUsuario", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.ActualizarUsuario")
    @ResponseWrapper(localName = "actualizarUsuarioResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.ActualizarUsuarioResponse")
    public OperationStatus actualizarUsuario(
            @WebParam(name = "usuario", targetNamespace = "")
            PrincipalContext usuario);

    /**
     * 
     * @param uid
     * @return
     *     returns wsclient.OperationPrincipalStatusContext
     */
    @WebMethod(action = "obtenerDatosUsuario")
    @WebResult(name = "obtenerDatosUsuario", targetNamespace = "")
    @RequestWrapper(localName = "obtenerDatosUsuario", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.ObtenerDatosUsuario")
    @ResponseWrapper(localName = "obtenerDatosUsuarioResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.ObtenerDatosUsuarioResponse")
    public OperationPrincipalStatusContext obtenerDatosUsuario(
            @WebParam(name = "uid", targetNamespace = "")
            String uid);

    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns wsclient.AuthenticationResponseContext
     * @throws SystemException_Exception
     */
    @WebMethod(action = "verifyCredentials")
    @WebResult(name = "verifyCredentials", targetNamespace = "")
    @RequestWrapper(localName = "verifyCredentials", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.VerifyCredentials")
    @ResponseWrapper(localName = "verifyCredentialsResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.VerifyCredentialsResponse")
    public AuthenticationResponseContext verifyCredentials(
            @WebParam(name = "login", targetNamespace = "")
            String login,
            @WebParam(name = "password", targetNamespace = "")
            String password)
        throws SystemException_Exception
    ;

    /**
     * 
     * @param uid
     * @return
     *     returns wsclient.OperationStatus
     */
    @WebMethod(action = "eliminarUsuarioporNombre")
    @WebResult(name = "eliminarUsuarioporNombre", targetNamespace = "")
    @RequestWrapper(localName = "eliminarUsuarioporNombre", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.EliminarUsuarioporNombre")
    @ResponseWrapper(localName = "eliminarUsuarioporNombreResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.EliminarUsuarioporNombreResponse")
    public OperationStatus eliminarUsuarioporNombre(
            @WebParam(name = "uid", targetNamespace = "")
            String uid);

    /**
     * 
     * @return
     *     returns wsclient.OperationPrincipalContextListStatus
     */
    @WebMethod(action = "listadoDeUsuarios")
    @WebResult(name = "listadoDeUsuarios", targetNamespace = "")
    @RequestWrapper(localName = "listadoDeUsuarios", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.ListadoDeUsuarios")
    @ResponseWrapper(localName = "listadoDeUsuariosResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.ListadoDeUsuariosResponse")
    public OperationPrincipalContextListStatus listadoDeUsuarios();

    /**
     * 
     * @param usuario
     * @return
     *     returns wsclient.OperationPrincipalStatusContext
     */
    @WebMethod(action = "crearUsuario")
    @WebResult(name = "crearUsuario", targetNamespace = "")
    @RequestWrapper(localName = "crearUsuario", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.CrearUsuario")
    @ResponseWrapper(localName = "crearUsuarioResponse", targetNamespace = "http://www.soaint.com/services/security-cartridge/1.0.0", className = "wsclient.CrearUsuarioResponse")
    public OperationPrincipalStatusContext crearUsuario(
            @WebParam(name = "usuario", targetNamespace = "")
            PrincipalContext usuario);

}
