CREATE TABLE TVS_PAIS (
  IDE_PAIS NUMBER NOT NULL,
  NOMBRE_PAIS varchar(255) DEFAULT NULL,
  COD_PAIS varchar(255) DEFAULT NULL,
  ESTADO varchar(255) DEFAULT NULL,
  FEC_CAMBIO TIMESTAMP  DEFAULT NULL,
  FEC_CREACION TIMESTAMP  DEFAULT NULL,
  COD_USUARIO_CREA varchar(255) DEFAULT NULL,
  PRIMARY KEY (IDE_PAIS)
)