export const ROUTES_PATH = {
  task: 'task',
  radicarCofEntrada: 'radicar-comunicaciones',
  radicarCofSalida: 'radicacion-salida',
  radicarDocumentoSalida: 'radicacion-documento_salida',
  digitalizarDocumento: 'digitalizar-documentos',
  adjuntarDocumento: 'adjuntar-documentos',
  gestionarDevoluciones: 'gestionar-devoluciones',
  corregirRadicacion: 'corregir-radicacion',
  dashboard: 'home',
  login: 'login',
  workspace: 'workspace',
  processList: 'process',
  asignacionComunicaciones: 'asignacion-comunicaciones',
  recibirGestionarComunicaciones: 'recibir-gestionar-comunicaciones',
  documentosTramite: 'documentos-tramite',
  cargaMasiva: 'carga-masiva',
  cargaMasivaDetails: 'carga-masiva/record/:id',
  distribucionFisica: 'distribucion-fisica',
  cargarPlanillas: 'cargar-planillas',
  produccionDocumentalMultiple: 'produccion-documental-multiple',
  produccionDocumental: 'producir-documento',
  archivarDocumento: 'archivar-documento',
  seleccionarUnidadDocumental: 'seleccionar-unidad-documental',
  seleccionarDocumentos: 'seleccionar-documentos',
  securityRole: 'security-role',
  gestionUnidadDocumental: 'gestion-unidad-documental',
  crearUnidadDocumental: 'crear-unidad-documental',
  disposicionFinal: 'disposicion-final',
  completarDatosDistribucion:"completar-datos-distribucion",
  transferenciasDocumentales:"transferencia-documentales",
  distribucionFisicaSalida:"distribucion-fisica-salida",
  cargarPlanillaSalida:"cargar-planilla-salida",

};
