export const ROUTES_PATH = {
  task: 'task',
  radicarCofEntrada: 'radicar-comunicaciones',
  radicarCofSalida: 'radicacion-salida',
  digitalizarDocumento: 'digitalizar-documentos',
  dashboard: 'home',
  login: 'login',
  workspace: 'workspace',
  processList: 'process',
  asignacionComunicaciones: 'asignacion-comunicaciones',
  recibirGestionarComunicaciones: 'recibir-gestionar-comunicaciones',
  documentosTramite: 'documentos-tramite',
  cargaMasiva: 'carga-masiva',
  cargaMasivaDetails: 'carga-masiva/record/:id',
  distribucionFisica: 'distribucion-fisica',
  cargarPlanillas: 'cargar-planillas',
  produccionDocumentalMultiple: 'produccion-documental-multiple',
  produccionDocumental: 'produccion-documental/:action',
};
