---------------------------------------------------------------------------------
  -- AJUSTES TABLE COR_CORRESPONDENCIA
  ---------------------------------------------------------------------------------

  /*ADICION DE DATOS */

INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES (176, 'TP-MCN', 'Normal', 'TP-MC', 'A ');
INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES (177, 'TP-MCC', 'Certificado', 'TP-MC', 'A ');
INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES (178, 'TP-CEL', 'Local', 'TP-CE', 'A ');
INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES (179, 'TP-CEN', 'Nacional', 'TP-CE', 'A ');
INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES (180, 'TP-CEI', 'Internacional', 'TP-CE', 'A ');
INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES (190, 'TP-CE', 'Tipo Clase de Envio', null, 'A ');
INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES (191, 'TP-MC', 'Tipo Modalidad de Correo', null, 'A ');