  ---------------------------------------------------------------------------------
  -- AJUSTES SOLICITADOS -  TVS_SOLICITUD_UNIDAD_DOCUMENTAL
  ---------------------------------------------------------------------------------

    -- ELIMINAR LA TABLA DE FUNCIONARIOS
  
	DROP TABLE TVS_SOLICITUD_UD;
	
	-- CREAR LAS SIQUIENTES TABLAS

CREATE TABLE TVS_SOLICITUD_UD
(
    IDE_SOLICITUD VARCHAR (8 BYTE) NOT NULL
  , ID VARCHAR2(8 BYTE) DEFAULT NULL
  , ID_CONSTANTE VARCHAR2(8 BYTE) DEFAULT NULL
  , FEC_HORA TIMESTAMP(6) NOT NULL
  , NOMBRE_UNIDAD_DOCUMENTAL VARCHAR2(50 BYTE) NOT NULL
  , DESCRIPTOR1 VARCHAR2(50 BYTE) NOT NULL
  , DESCRIPTOR2 VARCHAR2(50 BYTE) NOT NULL
  , NRO VARCHAR2(50 BYTE) DEFAULT NULL
  , CODIGO_SERIE VARCHAR2(50 BYTE) NOT NULL
  , CODIGO_SUBSERIE VARCHAR2(50 BYTE) NOT NULL
  , CODIGO_SEDE VARCHAR2(50 BYTE) NOT NULL
  , CODIGO_DEPENDENCIA VARCHAR2(50 BYTE) NOT NULL
  , ID_SOLICITANTE VARCHAR2(8 BYTE) NOT NULL
  , ESTADO VARCHAR2(2 BYTE) DEFAULT NULL
  , ACCION VARCHAR2(50 BYTE) DEFAULT NULL
  , OBSERVACIONES VARCHAR2(50 BYTE) DEFAULT NULL
) ;

---------------------------------------------------------------------------------
-- AJUSTES SOLICITADOS -  CONSTANTES
---------------------------------------------------------------------------------

-- INSERTAR CONSTANTES

INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('200', 'TP-ACS', 'Tipo Accion Solicitud Unidad Doumental', NULL , 'A');
INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('201', 'TP-ACSNR', 'No Revisada', 'TP-ACS', 'A');
INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('202', 'TP-ACSC', 'Creada', 'TP-ACS', 'A');
INSERT INTO TVS_CONSTANTES (IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO) VALUES ('203', 'TP-ACSNT', 'No Tramitada', 'TP-ACS', 'A');

	
	
  