DELETE FROM TABLE_GENERATOR;
INSERT INTO TABLE_GENERATOR VALUES ('COR_CORRESPONDENCIA_SEQ', '1');
INSERT INTO TABLE_GENERATOR VALUES ('COR_AGENTE_SEQ', '1');
INSERT INTO TABLE_GENERATOR VALUES ('COR_REFERIDO_SEQ', '1');
INSERT INTO TABLE_GENERATOR VALUES ('PPD_DOCUMENTO_SEQ', '1');
INSERT INTO TABLE_GENERATOR VALUES ('COR_ANEXO_SEQ', '1');
INSERT INTO TABLE_GENERATOR VALUES ('TVS_DATOS_CONTACTO_SEQ', '1');
INSERT INTO TABLE_GENERATOR VALUES ('PPD_TRAZ_DOCUMENTO_SEQ', '1');