export const PERSONA_ANONIMA = 'TP-PERA';
export const PERSONA_JURIDICA = 'TP-PERPJ';
export const PERSONA_NATURAL = 'TP-PERPN';
export const COMUNICACION_EXTERNA = 'TP-CMCOE';
export const COMUNICACION_INTERNA = 'TP-CMCOI';

export const DESTINATARIO_PRINCIPAL = 'TP-DESP';

export const TIPO_AGENTE_REMITENTE = 'REM';
export const TIPO_AGENTE_DESTINATARIO = 'DES';

export const TIPO_REMITENTE_INTERNO = 'INT';
export const TIPO_REMITENTE_EXTERNO = 'EXT';

export const DATOS_CONTACTO_PRINCIPAL = 'P';
export const DATOS_CONTACTO_SECUNDARIO = 'S';

export const TPDOC_NRO_IDENTIFICACION_TRIBUTARIO = 'TP-DOCN';
export const TPDOC_CEDULA_CIUDADANIA = 'TP-DOCCC';



