export const PERSONA_ANONIMA = 'TP-PERA';
export const PERSONA_JURIDICA = 'TP-PERPJ';
export const PERSONA_NATURAL = 'TP-PERPN';
export const COMUNICACION_EXTERNA = 'EE';
export const COMUNICACION_INTERNA = 'EI';
export const COMUNICACION_EXTERNA_ENVIADA = 'SE';
export const COMUNICACION_INTERNA_ENVIADA = 'SI';

export const DESTINATARIO_PRINCIPAL = 'TP-DESP';
export const DESTINATARIO_INTERNO = 'INTERNO';
export const DESTINATARIO_EXTERNO = 'EXTERNO';

export const TIPO_AGENTE_REMITENTE = 'TP-AGEE';
export const TIPO_AGENTE_DESTINATARIO = 'TP-AGEI';

export const TIPO_REMITENTE_INTERNO = 'INT';
export const TIPO_REMITENTE_EXTERNO = 'EXT';

export const DATOS_CONTACTO_PRINCIPAL = 'P';
export const DATOS_CONTACTO_SECUNDARIO = 'S';

export const TPDOC_NRO_IDENTIFICACION_TRIBUTARIO = 'TP-DOCN';
export const TPDOC_CEDULA_CIUDADANIA = 'TP-DOCCC';

export const MEDIO_RECEPCION_EMPRESA_MENSAJERIA = 'ME-RECEM';

export  const RADICACION_ENTRADA = "radicacion-entrada";
export  const RADICACION_SALIDA = "radicacion-salida";



