CREATE TABLE TVS_PAIS (
  IDE_PAIS NUMBER NOT NULL,
  NOMBRE_PAIS varchar(255) DEFAULT NULL,
  COD_PAIS varchar(255) DEFAULT NULL,
  ESTADO varchar(255) DEFAULT NULL,
  FEC_CAMBIO TIMESTAMP  DEFAULT NULL,
  FEC_CREACION TIMESTAMP  DEFAULT NULL,
  COD_USUARIO_CREA varchar(255) DEFAULT NULL,
  PRIMARY KEY (IDE_PAIS)
);
CREATE TABLE TABLE_GENERATOR (
  SEQ_NAME varchar(255) NOT NULL,
  SEQ_VALUE BIGINT  NOT NULL,
  PRIMARY KEY (SEQ_NAME)
);
CREATE TABLE TVS_MUNICIPIO(
IDE_MUNIC NUMBER NOT NULL,
NOMBRE_MUNIC varchar(255) DEFAULT NULL,
COD_MUNIC varchar(255) DEFAULT NULL,
COD_DEPAR varchar(255) DEFAULT NULL,
ESTADO varchar(255) DEFAULT NULL,
FEC_CAMBIO TIMESTAMP DEFAULT NULL ,
FEC_CREACION TIMESTAMP DEFAULT NULL ,
COD_USUARIO_CREA varchar(255) DEFAULT NULL,
PRIMARY  KEY (IDE_MUNIC)
);

CREATE TABLE TVS_DEPARTAMENTO(
IDE_DEPAR NUMBER NOT NULL ,
NOMBRE_DEPAR varchar(255) DEFAULT NULL,
COD_DEPAR varchar(255) DEFAULT NULL,
COD_PAIS varchar(255) DEFAULT NULL,
ESTADO varchar(255) DEFAULT NULL,
FEC_CAMBIO TIMESTAMP DEFAULT NULL ,
FEC_CREACION TIMESTAMP DEFAULT NULL ,
COD_USUARIO_CREA varchar(255) DEFAULT NULL,
PRIMARY  KEY (IDE_DEPAR)
);

CREATE TABLE TVS_CONSTANTES(
IDE_CONST NUMBER NOT NULL,
CODIGO varchar(255) DEFAULT NULL,
NOMBRE varchar(255) DEFAULT NULL,
COD_PADRE varchar(255) DEFAULT NULL,
ESTADO varchar(255) DEFAULT NULL,
PRIMARY  KEY (IDE_CONST)
);