CREATE TABLE TVS_PAIS (
  IDE_PAIS NUMBER NOT NULL,
  NOMBRE_PAIS varchar(255) DEFAULT NULL,
  COD_PAIS varchar(255) DEFAULT NULL,
  ESTADO varchar(255) DEFAULT NULL,
  FEC_CAMBIO TIMESTAMP  DEFAULT NULL,
  FEC_CREACION TIMESTAMP  DEFAULT NULL,
  COD_USUARIO_CREA varchar(255) DEFAULT NULL,
  PRIMARY KEY (IDE_PAIS)
);
CREATE TABLE TABLE_GENERATOR (
  SEQ_NAME varchar(255) NOT NULL,
  SEQ_VALUE BIGINT  NOT NULL,
  PRIMARY KEY (SEQ_NAME)
);
CREATE TABLE TVS_MUNICIPIO(
IDE_MUNIC NUMBER NOT NULL,
NOMBRE_MUNIC varchar(255) DEFAULT NULL,
COD_MUNIC varchar(255) DEFAULT NULL,
COD_DEPAR varchar(255) DEFAULT NULL,
ESTADO varchar(255) DEFAULT NULL,
FEC_CAMBIO TIMESTAMP DEFAULT NULL ,
FEC_CREACION TIMESTAMP DEFAULT NULL ,
COD_USUARIO_CREA varchar(255) DEFAULT NULL,
PRIMARY  KEY (IDE_MUNIC)
);

CREATE TABLE TVS_DEPARTAMENTO(
IDE_DEPAR NUMBER NOT NULL ,
NOMBRE_DEPAR varchar(255) DEFAULT NULL,
COD_DEPAR varchar(255) DEFAULT NULL,
COD_PAIS varchar(255) DEFAULT NULL,
ESTADO varchar(255) DEFAULT NULL,
FEC_CAMBIO TIMESTAMP DEFAULT NULL ,
FEC_CREACION TIMESTAMP DEFAULT NULL ,
COD_USUARIO_CREA varchar(255) DEFAULT NULL,
PRIMARY  KEY (IDE_DEPAR)
);

CREATE TABLE TVS_CONSTANTES(
IDE_CONST NUMBER NOT NULL,
CODIGO varchar(255) DEFAULT NULL,
NOMBRE varchar(255) DEFAULT NULL,
COD_PADRE varchar(255) DEFAULT NULL,
ESTADO varchar(255) DEFAULT NULL,
PRIMARY  KEY (IDE_CONST)
);

CREATE TABLE FUNCIONARIOS(
IDE_FUNCI NUMBER NOT NULL,
COD_TIP_DOC_IDENT varchar(255) DEFAULT NULL,
NRO_IDENTIFICACION varchar(255) DEFAULT NULL,
NOM_FUNCIONARIO varchar(255) DEFAULT NULL,
VAL_APELLIDO1 varchar(255) DEFAULT NULL,
VAL_APELLIDO2 varchar(255) DEFAULT NULL,
COD_CARGO varchar(255) DEFAULT NULL,
CORR_ELECTRONICO varchar(255) DEFAULT NULL,
COD_ORGA_ADMI varchar(255) DEFAULT NULL,
LOGIN_NAME varchar(255) DEFAULT NULL,
ESTADO varchar(255) DEFAULT NULL,
PRIMARY  KEY (IDE_FUNCI)
);

CREATE TABLE TVS_ORGANIGRAMA_ADMINISTRATIVO (
IDE_ORGA_ADMIN NUMBER NOT NULL ,
COD_ORG varchar(255) NOT NULL ,
NOM_ORG varchar(255) NOT NULL ,
DESC_ORG varchar(255) NOT NULL ,
IND_ES_ACTIVO varchar(255) NOT NULL ,
IDE_DIRECCION varchar(255) NULL ,
IDE_PLAN_RESPONSABLE NUMBER NULL ,
IDE_ORGA_ADMIN_PADRE varchar(255) NULL ,
COD_NIVEL varchar(255) NULL ,
FEC_CREACION TIMESTAMP NULL ,
IDE_USUARIO_CREO NUMBER NULL ,
IDE_USUARIO_CAMBIO NUMBER NOT NULL ,
FEC_CAMBIO TIMESTAMP NULL ,
NIV_LECTURA NUMBER NULL ,
NIV_ESCRITURA NUMBER NULL ,
IDE_UUID varchar(255) NULL ,
VAL_SISTEMA varchar(255) NULL ,
VAL_VERSION varchar(255) NULL ,
PRIMARY  KEY (IDE_ORGA_ADMIN)
)