DELETE FROM TVS_PAIS;
INSERT INTO TVS_PAIS(IDE_PAIS, NOMBRE_PAIS,COD_PAIS,ESTADO,FEC_CAMBIO,FEC_CREACION,COD_USUARIO_CREA)
       VALUES (1, 'CUBA', 'CUBA', 'ACTIVO',NULL,NULL,'USER1');
DELETE FROM TABLE_GENERATOR;
INSERT INTO TABLE_GENERATOR(SEQ_NAME, SEQ_VALUE)
       VALUES ('TVS_PAIS_SEQ', 1);

DELETE FROM TVS_MUNICIPIO;
INSERT INTO TVS_MUNICIPIO(IDE_MUNIC, NOMBRE_MUNIC, COD_MUNIC,COD_DEPAR,ESTADO,FEC_CAMBIO,FEC_CREACION,COD_USUARIO_CREA)
       VALUES ('1', 'MUNICIPIO1','CODIGO1','CODIGODEPTO1','ACTIVO',NULL, NULL ,'USER1');
INSERT INTO TVS_MUNICIPIO(IDE_MUNIC, NOMBRE_MUNIC, COD_MUNIC,COD_DEPAR,ESTADO,FEC_CAMBIO,FEC_CREACION,COD_USUARIO_CREA)
       VALUES ('2', 'MUNICIPIO2','CODIGO2','CODIGODEPTO2','ACTIVO',NULL, NULL ,'USER1');



DELETE  FROM TVS_DEPARTAMENTO;
INSERT  INTO TVS_DEPARTAMENTO (IDE_DEPAR,NOMBRE_DEPAR,COD_DEPAR, COD_PAIS, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA)
        VALUES ('1', 'DEPARTAMENTO1','CODIGODEPTO1','CODIGOPAIS1','ACTIVO',NULL, NULL ,'USER1');
INSERT  INTO TVS_DEPARTAMENTO (IDE_DEPAR,NOMBRE_DEPAR,COD_DEPAR, COD_PAIS, ESTADO, FEC_CAMBIO, FEC_CREACION, COD_USUARIO_CREA)
        VALUES ('2', 'DEPARTAMENTO2','CODIGODEPTO2','CODIGOPAIS2','ACTIVO',NULL, NULL ,'USER1');


DELETE FROM TVS_CONSTANTES;
INSERT INTO TVS_CONSTANTES(IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO)
       VALUES ('1','CODIGO1','NOMBRE1','CODIGOPADRE1','ACTIVO');
INSERT INTO TVS_CONSTANTES(IDE_CONST, CODIGO, NOMBRE, COD_PADRE, ESTADO)
       VALUES ('2','CODIGO2','NOMBRE2','CODIGOPADRE1','INACTIVO');

DELETE FROM FUNCIONARIOS;
INSERT INTO FUNCIONARIOS(IDE_FUNCI, COD_TIP_DOC_IDENT, NRO_IDENTIFICACION, NOM_FUNCIONARIO, VAL_APELLIDO1, VAL_APELLIDO2,
                          CORR_ELECTRONICO, LOGIN_NAME, ESTADO)
       VALUES ('1','COD_TIP_DOC_IDENT','NRO_IDENTIFICACION','NOM_FUNCIONARIO1','VAL_APELLIDO1','VAL_APELLIDO2','CORR_ELECTRONICO',
              'LOGIN_NAME','ACTIVO');
INSERT INTO FUNCIONARIOS(IDE_FUNCI, COD_TIP_DOC_IDENT, NRO_IDENTIFICACION, NOM_FUNCIONARIO, VAL_APELLIDO1, VAL_APELLIDO2,
                          CORR_ELECTRONICO, LOGIN_NAME, ESTADO)
       VALUES ('2','COD_TIP_DOC_IDENT','NRO_IDENTIFICACION','NOM_FUNCIONARIO1','VAL_APELLIDO1','VAL_APELLIDO2','CORR_ELECTRONICO',
              'LOGIN_NAME1','INACTIVO');

DELETE FROM TVS_ORGANIGRAMA_ADMINISTRATIVO;
INSERT INTO TVS_ORGANIGRAMA_ADMINISTRATIVO (IDE_ORGA_ADMIN, COD_ORG, NOM_ORG, DESC_ORG, IND_ES_ACTIVO, COD_NIVEL, IDE_USUARIO_CAMBIO)
VALUES ('1', '1', 'DIRECCION DE IMPUESTOS Y ADUANAS NACIONALES', 'DIRECCION DE IMPUESTOS Y ADUANAS NACIONALES', '1', '0', '1');

INSERT INTO TVS_ORGANIGRAMA_ADMINISTRATIVO (IDE_ORGA_ADMIN, COD_ORG, NOM_ORG, DESC_ORG, IND_ES_ACTIVO, IDE_ORGA_ADMIN_PADRE, COD_NIVEL, IDE_USUARIO_CAMBIO)
VALUES ('2', '101201403', 'GIT GES JURIDICA', 'GRUPO INTERNO DE TRABAJO DE GESTION JURIDICA', '1', '1', '1', '1');

DELETE FROM COR_PLANILLAS;
INSERT INTO COR_PLANILLAS (IDE_PLANILLA,NRO_PLANILLA,FEC_GENERACION,COD_TIPO_PLANILLA,COD_FUNC_GENERA,COD_SEDE_ORIGEN,COD_DEPENDENCIA_ORIGEN,COD_SEDE_DESTINO,COD_DEPENDENCIA_DESTINO,COD_CLASE_ENVIO,COD_MODALIDAD_ENVIO,FECHA_CREA,COD_USUARIO_CREA,FECHA_MODIF,COD_USUARIO_MODIF,IDE_ECM)
VALUES ('100','104000000000001',NULL,NULL,'1','1040','10401040','1040','10401040',NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO COR_PLANILLAS (IDE_PLANILLA,NRO_PLANILLA,FEC_GENERACION,COD_TIPO_PLANILLA,COD_FUNC_GENERA,COD_SEDE_ORIGEN,COD_DEPENDENCIA_ORIGEN,COD_SEDE_DESTINO,COD_DEPENDENCIA_DESTINO,COD_CLASE_ENVIO,COD_MODALIDAD_ENVIO,FECHA_CREA,COD_USUARIO_CREA,FECHA_MODIF,COD_USUARIO_MODIF,IDE_ECM)
VALUES ('200','104000000000002',NULL,NULL,'1','1040','10401040','1040','10401040',NULL,NULL,NULL,NULL,NULL,NULL,NULL);

DELETE FROM COR_AGENTE;
INSERT INTO COR_AGENTE (IDE_AGENTE, IDE_DOCUMENTO, COD_TIPO_REMITE, COD_TIPO_PERS, NOMBRE, RAZON_SOCIAL, NIT, COD_CORTESIA, COD_EN_CALIDAD, COD_TIP_DOC_IDENT, NRO_DOCU_IDENTIDAD, COD_SEDE, COD_DEPENDENCIA, COD_ESTADO, FEC_ASIGNACION, COD_TIP_AGENT, IND_ORIGINAL, FEC_CREACION, ESTADO_DISTRIBUCION)
VALUES ('100','836','EXT','TP-PERPN','NOMBRE EXT','RS','NIT','CC','CEC','CTDI','NDI','CS','CD','AS',NULL,'TP-AGEE',NULL,NULL,NULL);

INSERT INTO COR_AGENTE (IDE_AGENTE, IDE_DOCUMENTO, COD_TIPO_REMITE, COD_TIPO_PERS, NOMBRE, RAZON_SOCIAL, NIT, COD_CORTESIA, COD_EN_CALIDAD, COD_TIP_DOC_IDENT, NRO_DOCU_IDENTIDAD, COD_SEDE, COD_DEPENDENCIA, COD_ESTADO, FEC_ASIGNACION, COD_TIP_AGENT, IND_ORIGINAL, FEC_CREACION, ESTADO_DISTRIBUCION)
VALUES ('200','837','INT','TP-PERPN','NOMBRE INT','RS','NIT','CC','CEC','CTDI','NDI','CS','CD','AS',NULL,'TP-AGEI',NULL,NULL,NULL);

DELETE FROM COR_CORRESPONDENCIA;
INSERT INTO COR_CORRESPONDENCIA (IDE_DOCUMENTO,DESCRIPCION,TIEMPO_RESPUESTA,COD_UNIDAD_TIEMPO,COD_MEDIO_RECEPCION,FEC_RADICADO,NRO_RADICADO,COD_TIPO_CMC,IDE_INSTANCIA,REQ_DIST_FISICA,COD_FUNC_RADICA,COD_SEDE,COD_DEPENDENCIA,REQ_DIGITA,COD_EMP_MSJ,NRO_GUIA,FEC_VEN_GESTION,COD_ESTADO)
VALUES ('836','Correspondencia 836','10','UNID-TID','ME-RECVN',NULL,'1040TP-CMCOE2017000001','TP-CMCOE','33144','0','1','1040','10401040','0',NULL,NULL,NULL,'AS');

INSERT INTO COR_CORRESPONDENCIA (IDE_DOCUMENTO,DESCRIPCION,TIEMPO_RESPUESTA,COD_UNIDAD_TIEMPO,COD_MEDIO_RECEPCION,FEC_RADICADO,NRO_RADICADO,COD_TIPO_CMC,IDE_INSTANCIA,REQ_DIST_FISICA,COD_FUNC_RADICA,COD_SEDE,COD_DEPENDENCIA,REQ_DIGITA,COD_EMP_MSJ,NRO_GUIA,FEC_VEN_GESTION,COD_ESTADO)
VALUES ('837','Correspondencia 837','10','UNID-TID','ME-RECVN',NULL,'1040TP-CMCOE2017000001','TP-CMCOE','33144','0','1','1040','10401040','0',NULL,NULL,NULL,'AS');