DELETE FROM TVS_PAIS;
INSERT INTO TVS_PAIS(IDE_PAIS, NOMBRE_PAIS,COD_PAIS,ESTADO,FEC_CAMBIO,FEC_CREACION,COD_USUARIO_CREA)
       VALUES (1, 'CUBA', 'CUBA', 'ACTIVO',NULL,NULL,'USER1');
DELETE FROM TABLE_GENERATOR;
INSERT INTO TABLE_GENERATOR(SEQ_NAME, SEQ_VALUE)
       VALUES ('TVS_PAIS_SEQ', 1);