CREATE TABLE SGDTEST.COR_PLANILLAS
(
    IDE_PLANILLA NUMBER(18) PRIMARY KEY NOT NULL,
    NRO_PLANILLA VARCHAR2(50) DEFAULT NULL
,
    FEC_GENERACION TIMESTAMP(6) DEFAULT NULL
,
    COD_TIPO_PLANILLA VARCHAR2(8) DEFAULT NULL
,
    COD_FUNC_GENERA VARCHAR2(8) DEFAULT NULL
,
    COD_SEDE_ORIGEN VARCHAR2(8) DEFAULT NULL
,
    COD_DEPENDENCIA_ORIGEN VARCHAR2(32) DEFAULT NULL
,
    COD_SEDE_DESTINO VARCHAR2(8) DEFAULT NULL
,
    COD_DEPENDENCIA_DESTINO VARCHAR2(8) DEFAULT NULL
,
    COD_CLASE_ENVIO VARCHAR2(8) DEFAULT NULL
,
    COD_MODALIDAD_ENVIO VARCHAR2(8) DEFAULT NULL
,
    FECHA_CREA TIMESTAMP(6) DEFAULT NULL
,
    COD_USUARIO_CREA VARCHAR2(20) DEFAULT NULL
,
    FECHA_MODIF TIMESTAMP(6) DEFAULT NULL
,
    COD_USUARIO_MODIF VARCHAR2(20) DEFAULT NULL
,
    IDE_ECM VARCHAR2(50)
);