@@script-2-table-generator.sql
@@script-3-cor-agente.sql
@@script-4-cor-anexo.sql
@@script-5-cor-correspondencia.sql
@@script-6-cor-plan_agen.sql
@@script-7-cor-planillas.sql
@@script-8-cor-referido.sql
@@script-9-dct-asig-ultimo.sql
@@script-10-dct-asignacion.sql
@@script-11-funcionario.sql
@@script-12-ppd-documento.sql
@@script-13-ppd-traz-documento.sql
@@script-14-tvs-constantes.sql
@@script-15-tvs-datos-contacto.sql
@@script-16-tvs-departamento.sql
@@script-17-tvs-dserial.sql
@@script-18-tvs-municipio.sql
@@script-19-tvs-organigrama-administrativo.sql
@@script-20-tvs-pais.sql